spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/gym?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 824655

zuul:
  ratelimit:
    enabled: true
    repository: redis
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 1 #optional - request number limit per refresh interval window
        refresh-interval: 60 #default value (in seconds)
        type: #optional
          - origin
    policy-list:
      api:
        - limit: 1000
          refresh-interval: 60
          type:
            - origin
  strip-prefix: true
  routes:
    api:
      path: /**
      url: forward:/

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql